{% set name = "winkerberos" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/winkerberos-{{ version }}.tar.gz
  sha256: cbc27fc0fd31a40c5222a8bbde28a92735bf8438c1ea5ae0a1f841ecc54737cb

build:
  skip: true  # [py<36]
  skip: true  # [not win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=61.0
    - pip
  run:
    - python

test:
  imports:
    - winkerberos
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mongodb-labs/winkerberos
  license: Apache-2.0
  license_file: LICENSE
  summary: High level interface to SSPI for Kerberos client auth
  license_family: Apache

extra:
  recipe-maintainers:
    - ocefpaf
